describe("Saved card user flows", () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
      .intercept({
        method: 'GET',
        url: 'https://smashbros-unofficial-api.vercel.app/api/v1/ultimate/characters',
        hostname: 'localhost'
      })
      .get('select')
      .select('Mario')
      .get('.submit-character-button')
      .click()
      .get('.rant-card')
      .get('.save-rant-button')
      .click()
  })

  it('Should hold onto saved cards when navigating to and from page', () => {
    cy.get('.saved-rants-link')
      .click()
      .get('.rant-card[id="1"]')
      .should('exist')
      .get('.home-link')
      .click()
      .get('.saved-rants-link')
      .click()
      .get('.rant-card[id="1"]')
      .should('exist')
  })

  it('Should be able to save multiple cards from the same character', () => {
    cy.get('select')
      .select('Link')
      .get('.submit-character-button')
      .click()
      .get('.rant-card')
      .get('.save-rant-button')
      .click()
      .get('.save-rant-button')
      .click()
      .get('.saved-rants-link')
      .click()
      .get('.rant-card[id="1"]')
      .should('exist')
      .get('.rant-card[id="2"]')
      .should('exist')
      .contains('Link')
      .get('.rant-card[id="3"]')
      .should('exist')
      .contains('Link')
  })

  it('Should display correct cards when changing characters multiple times', () => {
    cy.get('select')
      .select('Link')
      .get('.submit-character-button')
      .click()
      .get('.rant-card')
      .get('.save-rant-button')
      .click()
      .get('select')
      .select('Ness')
      .get('.submit-character-button')
      .click()
      .get('.rant-card')
      .get('.save-rant-button')
      .click()
      .get('select')
      .select('Samus')
      .get('.submit-character-button')
      .click()
      .get('.rant-card')
      .should('exist')
      .get('.save-rant-button')
      .click()
      .get('.saved-rants-link')
      .click()
      .get('.rant-card[id="1"]')
      .should('exist')
      .contains('Mario')
      .get('.rant-card[id="2"]')
      .should('exist')
      .contains('Link')
      .get('.rant-card[id="3"]')
      .should('exist')
      .contains('Ness')
      .get('.rant-card[id="4"]')
      .should('exist')
      .contains('Samus')
  })
});
